# SPDX-FileCopyrightText: 2026 Sascha Brawer <sascha@brawer.ch>
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    groups:
      npm-dependencies:
        patterns: ["*"]
