// SPDX-FileCopyrightText: 2026 Sascha Brawer <sascha@brawer.ch>
// SPDX-License-Identifier: MIT

package main

import (
	"bytes"
	"crypto/sha256"
	"crypto/sha512"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"strconv"
	"time"

	"github.com/google/uuid"
)

// This file produces a CycloneDX 1.7 Bill of Materials describing one dated
// GeoTIFF: the exact bytes that were produced (SHA-256 and SHA-512) and the
// software revision that produced them. The builder uploads it next to the
// GeoTIFF as public/osmviews-<date>.cdx.json, before the GeoTIFF itself, so a
// consumer that can fetch a given version can always fetch its BOM. See
// https://github.com/brawer/osmviews/issues/87.
//
// The BOM is generated by hand rather than with a CycloneDX library to keep
// the dependency surface small and the output byte-stable: encoding/json
// emits struct fields in declaration order, and every input is deterministic
// (the version date, not the wall clock).

const (
	bomSpecVersion = "1.7"
	bomSchema      = "http://cyclonedx.org/schema/bom-1.7.schema.json"

	bomDownloadURL = "https://osmviews.toolforge.org/download/osmviews.tiff"
	bomWebsiteURL  = "https://osmviews.toolforge.org"
	bomVCSURL      = "https://github.com/brawer/osmviews"
	bomBuildSysURL = "https://github.com/brawer/osmviews/actions"
	bomTileLogsURL = "https://planet.openstreetmap.org/tile_logs/"

	// bomTileLogsLicenseURL points at the OSM Foundation Licensing Working
	// Group minutes confirming that the tile logs are in the public domain.
	bomTileLogsLicenseURL = "https://osmfoundation.org/wiki/Licensing_Working_Group/Minutes/2022-05-12#Using_tile_logs_for_ranking_a_non-ODbL_dataset"

	// bomSupplier{Name,URL} identify the supplier of both the GeoTIFF and the
	// pipeline. NTIA "minimum elements" require a supplier for the document
	// and every component.
	bomSupplierName = "Sascha Brawer"
	bomSupplierURL  = "https://brawer.ch"

	// bomRepoSlug is the "<namespace>/<name>" of the pkg:github Package-URL
	// for the pipeline; bomModuleGroup is the Go module path, used as the
	// CycloneDX component group.
	bomRepoSlug    = "brawer/osmviews"
	bomModuleGroup = "github.com/brawer/osmviews"

	bomCRS = "EPSG:3857"
)

// bomNamespace is a fixed, arbitrary UUID. The BOM's serialNumber is a
// version-5 (SHA-1) UUID derived from it and the GeoTIFF's SHA-256, so an
// identical GeoTIFF always yields an identically identified BOM.
var bomNamespace = uuid.MustParse("7bd9f8e0-1c3a-4b6d-9e2f-0a1b2c3d4e5f")

// bomInputs is everything writeBOM needs about one build. Every field is
// deterministic; nothing is read from the wall clock.
type bomInputs struct {
	Date     time.Time // last ingested tile-log day; the version identity
	FirstDay time.Time // earliest ingested tile-log day
	Weeks    int       // number of weekly logs aggregated
	SHA256   string    // lower-case hex digest of the GeoTIFF
	SHA512   string    // lower-case hex digest of the GeoTIFF
	Software string    // resolved Software tag, e.g. "OSMViews/v0.1.2+1a2b3c4d5e6f"
	Revision string    // full VCS revision, or "" if the build recorded none
	Modified bool      // whether the working tree was dirty
	Release  string    // released version, e.g. "0.1.2", or ""
	MaxZoom  int       // deepest zoom level in the GeoTIFF
}

// hashFile returns the lower-case hex SHA-256 and SHA-512 digests of the file
// at path, read in a single pass.
func hashFile(path string) (sha256hex, sha512hex string, err error) {
	f, err := os.Open(path)
	if err != nil {
		return "", "", err
	}
	defer f.Close()

	h256 := sha256.New()
	h512 := sha512.New()
	if _, err := io.Copy(io.MultiWriter(h256, h512), f); err != nil {
		return "", "", err
	}
	return hex.EncodeToString(h256.Sum(nil)), hex.EncodeToString(h512.Sum(nil)), nil
}

// writeBOM builds the CycloneDX BOM for in and writes it to path, atomically.
func writeBOM(path string, in bomInputs) error {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false) // keep '&' in the purl query literal
	enc.SetIndent("", "  ")
	if err := enc.Encode(buildBOM(in)); err != nil {
		return err
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// softwarePURL is the Package-URL of the pipeline that produced the GeoTIFF.
// It prefers the exact commit; if the build recorded no revision it falls
// back to the release tag, and if there is neither it returns "".
func (in bomInputs) softwarePURL() string {
	switch {
	case in.Revision != "":
		return "pkg:github/" + bomRepoSlug + "@" + in.Revision
	case in.Release != "":
		return "pkg:github/" + bomRepoSlug + "@v" + in.Release
	default:
		return ""
	}
}

// dataPURL is the Package-URL of the GeoTIFF itself: a generic package
// pinned by version date, carrying its SHA-256 and download URL as
// qualifiers (sorted, as the purl spec requires).
func (in bomInputs) dataPURL() string {
	return fmt.Sprintf("pkg:generic/osmviews@%s?checksum=sha256:%s&download_url=%s",
		in.Date.UTC().Format("2006-01-02"), in.SHA256, url.QueryEscape(bomDownloadURL))
}

// bomSupplier is the organizational entity recorded as supplier of the
// document and of every component (NTIA minimum element).
func bomSupplier() *cdxOrgEntity {
	return &cdxOrgEntity{Name: bomSupplierName, URL: []string{bomSupplierURL}}
}

func buildBOM(in bomInputs) *cdxBOM {
	date := in.Date.UTC().Format("2006-01-02")
	dataRef := "osmviews-geotiff-" + in.Date.UTC().Format("20060102")
	const builderRef = "osmviews-builder"

	builderProps := []cdxProperty{{Name: "osmviews:software", Value: in.Software}}
	if in.Revision != "" {
		builderProps = append(builderProps,
			cdxProperty{Name: "osmviews:vcs:revision", Value: in.Revision},
			cdxProperty{Name: "osmviews:vcs:modified", Value: strconv.FormatBool(in.Modified)})
	}
	if in.Release != "" {
		builderProps = append(builderProps,
			cdxProperty{Name: "osmviews:release", Value: in.Release})
	}

	// The pipeline is a tool that produced both the GeoTIFF and this BOM, not
	// a component the GeoTIFF depends on. It therefore lives in metadata.tools
	// and is referenced from the formulation workflow below.
	builderTool := cdxComponent{
		Type:      "application",
		BOMRef:    builderRef,
		Supplier:  bomSupplier(),
		Name:      "osmviews-builder",
		Group:     bomModuleGroup,
		Version:   in.Release,
		Publisher: bomSupplierName,
		PURL:      in.softwarePURL(),
		Licenses:  []cdxLicenseChoice{{License: cdxLicense{ID: "MIT"}}},
		ExternalReferences: []cdxExternalRef{
			{Type: "vcs", URL: bomVCSURL},
			{Type: "build-system", URL: bomBuildSysURL},
		},
		Properties: builderProps,
	}

	data := cdxComponent{
		Type:     "data",
		BOMRef:   dataRef,
		Supplier: bomSupplier(),
		Name:     "osmviews",
		Version:  date,
		Description: fmt.Sprintf(
			"OpenStreetMap view density, in weekly user views per km2 "+
				"(Cloud-Optimized GeoTIFF, %s, zoom 0-%d).", bomCRS, in.MaxZoom),
		PURL:     in.dataPURL(),
		Licenses: []cdxLicenseChoice{{License: cdxLicense{ID: "CC0-1.0"}}},
		Hashes: []cdxHash{
			{Alg: "SHA-256", Content: in.SHA256},
			{Alg: "SHA-512", Content: in.SHA512},
		},
		ExternalReferences: []cdxExternalRef{
			{Type: "distribution", URL: bomDownloadURL},
			{Type: "website", URL: bomWebsiteURL},
			{Type: "vcs", URL: bomVCSURL},
		},
		Data: []cdxComponentData{
			{
				BOMRef:         "osmviews-dataset-" + in.Date.UTC().Format("20060102"),
				Type:           "dataset",
				Name:           "OpenStreetMap tile view density",
				Classification: "PUBLIC",
			},
		},
		Properties: []cdxProperty{
			{Name: "osmviews:tileLogs:firstDay", Value: in.FirstDay.UTC().Format("2006-01-02")},
			{Name: "osmviews:tileLogs:lastDay", Value: date},
			{Name: "osmviews:tileLogs:weeks", Value: strconv.Itoa(in.Weeks)},
			{Name: "osmviews:raster:crs", Value: bomCRS},
			{Name: "osmviews:raster:maxZoom", Value: strconv.Itoa(in.MaxZoom)},
		},
	}

	// The upstream data the GeoTIFF is derived from: OpenStreetMap tile logs.
	// This is a genuine data->data dependency (distinct from osmviews-builder,
	// which is a tool and belongs in the formulation). The OSM Foundation
	// Licensing Working Group has confirmed the logs are in the public domain
	// (see the minutes linked as a "license" external reference).
	const tileLogsRef = "osm-tilelogs"
	tileLogs := cdxComponent{
		Type:     "data",
		BOMRef:   tileLogsRef,
		Supplier: &cdxOrgEntity{Name: "OpenStreetMap Foundation", URL: []string{"https://osmfoundation.org"}},
		Name:     "OpenStreetMap tile logs",
		// Upstream publishes one xz-compressed text file per day. The "version"
		// is the last day this build ingested, matching the GeoTIFF's own
		// version; the ingested date range is in the properties.
		Version:     date,
		Description: "Per-tile access counts, one xz-compressed text file per day (tiles-YYYY-MM-DD.txt.xz).",
		PURL: "pkg:generic/openstreetmap/tile-logs@" + date +
			"?download_url=" + url.QueryEscape(bomTileLogsURL),
		Licenses: []cdxLicenseChoice{{License: cdxLicense{
			ID:              "CC0-1.0",
			Acknowledgement: "concluded",
			URL:             bomTileLogsLicenseURL,
		}}},
		ExternalReferences: []cdxExternalRef{
			{Type: "distribution", URL: bomTileLogsURL},
			{Type: "license", URL: bomTileLogsLicenseURL,
				Comment: "OSM Foundation Licensing Working Group minutes confirming the tile logs are in the public domain."},
		},
		Data: []cdxComponentData{{
			BOMRef:         "osm-tilelogs-dataset",
			Type:           "dataset",
			Name:           "OpenStreetMap tile access logs",
			Classification: "PUBLIC",
		}},
		Properties: []cdxProperty{
			{Name: "osmviews:tileLogs:firstDay", Value: in.FirstDay.UTC().Format("2006-01-02")},
			{Name: "osmviews:tileLogs:lastDay", Value: date},
		},
	}

	// Formulation: how the GeoTIFF was produced. A single build workflow that
	// consumes the OpenStreetMap tile logs and emits the GeoTIFF, using the
	// osmviews-builder tool. This is the CycloneDX-correct place for the
	// producing step; the only dependency-graph edge is the source data.
	workflow := cdxWorkflow{
		BOMRef: "osmviews-build-workflow-" + in.Date.UTC().Format("20060102"),
		UID:    "osmviews-build-" + in.Date.UTC().Format("20060102"),
		Name:   "OSMViews weekly GeoTIFF build",
		Description: fmt.Sprintf("Aggregates %d weeks of OpenStreetMap tile-access logs "+
			"(%s..%s) into the Cloud-Optimized GeoTIFF.",
			in.Weeks, in.FirstDay.UTC().Format("2006-01-02"), date),
		ResourceReferences: []cdxResourceRef{{Ref: builderRef}},
		TaskTypes:          []string{"build"},
		Inputs: []cdxWorkflowIO{{
			Resource: &cdxResourceRef{Ref: tileLogsRef},
		}},
		Outputs: []cdxWorkflowIO{{
			Type:     "artifact",
			Resource: &cdxResourceRef{Ref: dataRef},
		}},
	}

	return &cdxBOM{
		Schema:       bomSchema,
		BOMFormat:    "CycloneDX",
		SpecVersion:  bomSpecVersion,
		SerialNumber: "urn:uuid:" + uuid.NewSHA1(bomNamespace, []byte(in.SHA256)).String(),
		Version:      1,
		Metadata: cdxMetadata{
			Timestamp:  in.Date.UTC().Format(time.RFC3339),
			Lifecycles: []cdxLifecycle{{Phase: "post-build"}},
			Supplier:   bomSupplier(),
			Tools:      cdxTools{Components: []cdxComponent{builderTool}},
			Component:  data,
		},
		Components: []cdxComponent{tileLogs},
		Dependencies: []cdxDependency{
			{Ref: dataRef, DependsOn: []string{tileLogsRef}},
			{Ref: tileLogsRef, DependsOn: []string{}},
		},
		Formulation: []cdxFormulation{{
			BOMRef:    "osmviews-build-" + in.Date.UTC().Format("20060102"),
			Workflows: []cdxWorkflow{workflow},
		}},
	}
}

// Minimal CycloneDX 1.7 JSON model, covering only the fields the builder
// emits. Field order is the JSON output order; keep it stable.

type cdxBOM struct {
	Schema       string           `json:"$schema"`
	BOMFormat    string           `json:"bomFormat"`
	SpecVersion  string           `json:"specVersion"`
	SerialNumber string           `json:"serialNumber"`
	Version      int              `json:"version"`
	Metadata     cdxMetadata      `json:"metadata"`
	Components   []cdxComponent   `json:"components"`
	Dependencies []cdxDependency  `json:"dependencies"`
	Formulation  []cdxFormulation `json:"formulation,omitempty"`
}

type cdxMetadata struct {
	Timestamp  string         `json:"timestamp"`
	Lifecycles []cdxLifecycle `json:"lifecycles"`
	Supplier   *cdxOrgEntity  `json:"supplier,omitempty"`
	Tools      cdxTools       `json:"tools"`
	Component  cdxComponent   `json:"component"`
}

type cdxLifecycle struct {
	Phase string `json:"phase"`
}

type cdxOrgEntity struct {
	Name string   `json:"name"`
	URL  []string `json:"url,omitempty"`
}

type cdxTools struct {
	Components []cdxComponent `json:"components"`
}

type cdxComponent struct {
	Type               string             `json:"type"`
	BOMRef             string             `json:"bom-ref,omitempty"`
	Supplier           *cdxOrgEntity      `json:"supplier,omitempty"`
	Name               string             `json:"name"`
	Group              string             `json:"group,omitempty"`
	Version            string             `json:"version,omitempty"`
	Description        string             `json:"description,omitempty"`
	Publisher          string             `json:"publisher,omitempty"`
	PURL               string             `json:"purl,omitempty"`
	Licenses           []cdxLicenseChoice `json:"licenses,omitempty"`
	Hashes             []cdxHash          `json:"hashes,omitempty"`
	ExternalReferences []cdxExternalRef   `json:"externalReferences,omitempty"`
	Data               []cdxComponentData `json:"data,omitempty"`
	Properties         []cdxProperty      `json:"properties,omitempty"`
}

type cdxLicenseChoice struct {
	License cdxLicense `json:"license"`
}

type cdxLicense struct {
	ID              string `json:"id,omitempty"`
	Name            string `json:"name,omitempty"`
	Acknowledgement string `json:"acknowledgement,omitempty"`
	URL             string `json:"url,omitempty"`
}

type cdxHash struct {
	Alg     string `json:"alg"`
	Content string `json:"content"`
}

type cdxExternalRef struct {
	Type    string `json:"type"`
	URL     string `json:"url"`
	Comment string `json:"comment,omitempty"`
}

type cdxComponentData struct {
	BOMRef         string `json:"bom-ref,omitempty"`
	Type           string `json:"type"`
	Name           string `json:"name,omitempty"`
	Classification string `json:"classification,omitempty"`
}

type cdxProperty struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type cdxDependency struct {
	Ref       string   `json:"ref"`
	DependsOn []string `json:"dependsOn"`
}

type cdxFormulation struct {
	BOMRef     string         `json:"bom-ref,omitempty"`
	Components []cdxComponent `json:"components,omitempty"`
	Workflows  []cdxWorkflow  `json:"workflows,omitempty"`
}

type cdxWorkflow struct {
	BOMRef             string           `json:"bom-ref"`
	UID                string           `json:"uid"`
	Name               string           `json:"name,omitempty"`
	Description        string           `json:"description,omitempty"`
	ResourceReferences []cdxResourceRef `json:"resourceReferences,omitempty"`
	TaskTypes          []string         `json:"taskTypes"`
	Inputs             []cdxWorkflowIO  `json:"inputs,omitempty"`
	Outputs            []cdxWorkflowIO  `json:"outputs,omitempty"`
}

type cdxResourceRef struct {
	Ref               string          `json:"ref,omitempty"`
	ExternalReference *cdxExternalRef `json:"externalReference,omitempty"`
}

// cdxWorkflowIO models both a CycloneDX inputType and outputType; Type is set
// only for outputs (e.g. "artifact").
type cdxWorkflowIO struct {
	Type     string          `json:"type,omitempty"`
	Resource *cdxResourceRef `json:"resource,omitempty"`
}
