// SPDX-FileCopyrightText: 2026 Sascha Brawer <sascha@brawer.ch>
// SPDX-License-Identifier: MIT

// Code generated by release-please. DO NOT EDIT.

package version

// Release is the released version a build was cut from. release-please sets
// it in the release commit (see RELEASING.md); it is "" on any other build,
// in which case Resolve falls back to the source revision.
const Release = "0.1.4" // x-release-please-version
