# Cronjob for running qrank-builder in production.
# SPDX-License-Identifier: MIT

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: osmviews-builder
  namespace: tool-qrank
  labels:
    name: qrank.osmviews-builder
    toolforge: tool
spec:
  concurrencyPolicy: Forbid  # don't start new jobs while old is still running
  schedule: "21 18 * * *"  # daily at 18:21
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          restartPolicy: OnFailure
          containers:
          - name: osmviews-builder
            workingDir: /data/project/qrank
            image: docker-registry.tools.wmflabs.org/toolforge-buster-standalone:latest
            command: [ "bin/osmviews-builder", "-storage-key=keys/storage-key" ]
            resources:
              requests:
                memory: "1.5Gi"
                cpu: "1"
              limits:
                memory: "1.5Gi"
                cpu: "1"
