# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
# SPDX-Licence-Identifier: MIT

name: Test, build, and deploy

on: [push, pull_request]

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -ldflags="-s -w" -v ./...
    - name: Test
      run: go test -v ./...
    - name: Deploy
      # if: startsWith(github.ref, 'refs/tags')
      run: |
          echo ${{github.ref}} ${{github.ref_name}}
          go build -ldflags="-s -w" -v ./...
          ls
          pwd
          printenv
          file osmviews-builder
